# Generated by Django 4.1.3 on 2022-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistic', '0002_alter_artwork_artwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_artist',
            field=models.BooleanField(null=True),
        ),
    ]
